import { Workbook } from "exceljs";
import { formatDate, formatDateTime } from "@/lib/formatters";
import type { LeadView } from "@/lib/lead-adapters";
import { leadGenderLabel } from "@/lib/lead-adapters";
import type { UserRole } from "@/lib/types";

const ROLE_LABELS: Record<UserRole, string> = {
  super_admin: "Super Admin",
  branch_manager: "Branch Manager",
  loan_officer: "Loan Officer",
  credit_analyst: "Credit Analyst",
  collections_officer: "Collections Officer",
  accountant: "Accountant",
  customer_service: "Customer Service",
};

export function roleDisplayLabel(role: string): string {
  return (
    ROLE_LABELS[role as UserRole] ??
    role
      .replace(/_/g, " ")
      .replace(/\b\w/g, (c) => c.toUpperCase())
  );
}

function slugify(value: string): string {
  return (
    value
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") || "user"
  );
}

export function leadsReportFilename(opts: { generatedByName: string; from: string; to: string }): string {
  return `Leads-Report-${slugify(opts.generatedByName)}-${opts.from}-to-${opts.to}.xlsx`;
}

const LAST_COLUMN = "H";
const BRAND_DARK = "FF065F46"; // emerald-800
const BRAND_MID = "FF047857"; // emerald-700
const HEADER_FILL = "FF059669"; // emerald-600
const STRIPE_FILL = "FFECFDF5"; // emerald-50
const LABEL_COLOR = "FF065F46"; // emerald-800
const BORDER_COLOR = "FFCBD5E1"; // slate-300

const THIN_BORDER = {
  top: { style: "thin" as const, color: { argb: BORDER_COLOR } },
  left: { style: "thin" as const, color: { argb: BORDER_COLOR } },
  bottom: { style: "thin" as const, color: { argb: BORDER_COLOR } },
  right: { style: "thin" as const, color: { argb: BORDER_COLOR } },
};

export interface LeadsReportOptions {
  leads: LeadView[];
  from: string;
  to: string;
  generatedByName: string;
  generatedByRole: string;
}

/** Builds the branded "Field Leads Report" workbook shown to admins/officers as an .xlsx download. */
export async function buildLeadsReportWorkbook(opts: LeadsReportOptions): Promise<Buffer> {
  const { leads, from, to, generatedByName, generatedByRole } = opts;

  const workbook = new Workbook();
  workbook.creator = "Falco Financial Services";
  workbook.created = new Date();

  const sheet = workbook.addWorksheet("Field Leads Report", {
    views: [{ showGridLines: false }],
  });

  sheet.columns = [
    { width: 7 },
    { width: 30 },
    { width: 18 },
    { width: 12 },
    { width: 16 },
    { width: 42 },
    { width: 30 },
    { width: 18 },
  ];

  function bandRow(rowNumber: number, text: string, fill: string, size: number, height: number) {
    sheet.getRow(rowNumber).height = height;
    sheet.mergeCells(`A${rowNumber}:${LAST_COLUMN}${rowNumber}`);
    const cell = sheet.getCell(`A${rowNumber}`);
    cell.value = text;
    cell.font = { bold: true, size, color: { argb: "FFFFFFFF" } };
    cell.alignment = { vertical: "middle", horizontal: "center" };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: fill } };
  }

  bandRow(1, "FALCO FINANCIAL SERVICES", BRAND_DARK, 15, 26);
  bandRow(2, "Field Leads Report", BRAND_MID, 12, 20);
  sheet.getRow(3).height = 8;

  function metaRow(rowNumber: number, label: string, value: string, valueOpts: { color?: string; bold?: boolean } = {}) {
    const labelCell = sheet.getCell(`A${rowNumber}`);
    labelCell.value = label;
    labelCell.font = { bold: true, color: { argb: LABEL_COLOR } };
    labelCell.alignment = { vertical: "middle" };

    sheet.mergeCells(`B${rowNumber}:${LAST_COLUMN}${rowNumber}`);
    const valueCell = sheet.getCell(`B${rowNumber}`);
    valueCell.value = value;
    valueCell.font = { bold: valueOpts.bold ?? false, color: { argb: valueOpts.color ?? "FF1F2937" } };
    valueCell.alignment = { vertical: "middle" };
  }

  metaRow(4, "Generated by:", `${generatedByName} (${roleDisplayLabel(generatedByRole)})`);
  metaRow(5, "Reporting period:", `${formatDate(from)} \u2013 ${formatDate(to)}`);
  metaRow(6, "Generated on:", formatDateTime(new Date().toISOString()));
  metaRow(7, "Total leads:", String(leads.length), { color: "FF047857", bold: true });

  sheet.getRow(8).height = 8;

  const headerRowNumber = 9;
  const headers = [
    "S/N",
    "Name of Customer",
    "Phone Number",
    "Gender",
    "Date Added",
    "Location",
    "Created By",
    "Creator Role",
  ];
  const headerRow = sheet.getRow(headerRowNumber);
  headerRow.height = 20;
  headers.forEach((label, idx) => {
    const cell = headerRow.getCell(idx + 1);
    cell.value = label;
    cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
    cell.alignment = { vertical: "middle", horizontal: idx === 0 ? "center" : "left" };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: HEADER_FILL } };
    cell.border = THIN_BORDER;
  });

  if (leads.length === 0) {
    const emptyRowNumber = headerRowNumber + 1;
    sheet.getRow(emptyRowNumber).height = 20;
    sheet.mergeCells(`A${emptyRowNumber}:${LAST_COLUMN}${emptyRowNumber}`);
    const cell = sheet.getCell(`A${emptyRowNumber}`);
    cell.value = "No leads were added in the selected period.";
    cell.font = { italic: true, color: { argb: "FF64748B" } };
    cell.alignment = { vertical: "middle", horizontal: "center" };
    cell.border = THIN_BORDER;
  } else {
    leads.forEach((lead, idx) => {
      const rowNumber = headerRowNumber + 1 + idx;
      const row = sheet.getRow(rowNumber);
      const dateAdded = lead.followUpDate || lead.createdAt;
      const values: Array<string | number> = [
        idx + 1,
        lead.fullName || "-",
        lead.phoneNumber || "-",
        lead.gender ? leadGenderLabel[lead.gender] : "-",
        dateAdded ? formatDate(dateAdded) : "-",
        lead.locationName || "-",
        lead.createdByName || lead.createdBy || "-",
        lead.createdByRole ? roleDisplayLabel(lead.createdByRole) : "-",
      ];
      values.forEach((value, colIdx) => {
        const cell = row.getCell(colIdx + 1);
        cell.value = value;
        cell.alignment = {
          vertical: "middle",
          horizontal: colIdx === 0 ? "center" : "left",
          wrapText: colIdx === 5 || colIdx === 6,
        };
        cell.border = THIN_BORDER;
        if (idx % 2 === 1) {
          cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: STRIPE_FILL } };
        }
      });
    });
  }

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}
